### ISSUE TITLE
Error 'empty namespace prefix is not supported in ElementPath' 

### ISSUE THREAD

**Issue by lylh** [rytilahti/python-songpal#6] opened 2018-02-04 09:27 UTC
Model Name: SRS-X77

> songpal discover
Discovering for 3 seconds
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.172:5000/ssdp/desc-DSM-eth0.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.172:50001/desc/device.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.172:50001/desc/device.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.172:50001/desc/device.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.172:50001/desc/device.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.172:50001/desc/device.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.172:50001/desc/device.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.1:14504/rootDesc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:54380/SRS-X77_DDD.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:54380/SRS-X77_DDD.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:54380/SRS-X77_DDD.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:54380/SRS-X77_DDD.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:54380/SRS-X77_DDD.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:54380/SRS-X77_DDD.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:54380/SRS-X77_DDD.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:54380/SRS-X77_DDD.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:8008/ssdp/device-desc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:8008/ssdp/device-desc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:8008/ssdp/device-desc.xml
ERROR:ssdp:Error 'empty namespace prefix is not supported in ElementPath' for http://192.168.123.35:8008/ssdp/device-desc.xml
android@localhost:~$ songpal --version
songpal, version 0.0.5

![image](https://user-images.githubusercontent.com/7277105/35776135-c5efffbc-09d1-11e8-8681-7f2f0a5279f5.png)

**Comment by rytilahti** [comment] 2018-02-04 14:23
https://github.com/flyte/upnpclient/issues/9 is a related upstream issue, that device doesn't respond with a valid XML. Could you please upload the contents of those files it fails to handle?

In the file you pasted there's no `X_ScalarWebAPI_BaseURL` available (in my soundbar it is listed in `http://192.168.1.1:52323/dmr.xml`), which points to the endpoint. 

What you can also do is to check if `http://192.168.123.172:10000/sony` or `http://192.168.123.172:54480` works for you as an endpoint (e.g. `songpal --endpoint http://192.168.123.172:10000/sony sysinfo`).

**Comment by rytilahti** [comment] 2018-02-14 11:30
Any news on this? Have you checked if those XML files mentioned in the errors contain relevant elements?

**Comment by lylh** [comment] 2018-03-03 10:14
@rytilahti  SRS-X77 endpoint : http://192.168.123.35:54480/sony 
`{
"error": [
404,
"Not Found"
]
}`

`homeassistant.components.discovery:Unknown service discovered: songpal {'port': 54380, 'name': 'SRS-X77 F82DA3', 'serial': None, 'model_name': 'SRS-X77', 'ssdp_description': 'http://192.168.123.35:54380/SRS-X77_DDD.xml', 'model_number': 'MINT1.9.1', 'properties': {'endpoint': 'http://192.168.123.35:54480/sony', 'scalarwebapi': {'X_ScalarWebAPI_BaseURL': 'http://192.168.123.35:54480/sony', 'X_ScalarWebAPI_Version': '1.0', 'X_ScalarWebAPI_ServiceList': {'X_ScalarWebAPI_ServiceType': ['guide', 'audio', 'avContent', 'system']}}}, 'host': '192.168.123.35'}`

**Comment by lylh** [comment] 2018-03-03 10:26
> 

> songpal --endpoint http://192.168.123.35:54480/sony source
Bluetooth Audio (extInput:btAudio)
  Got an error for getContentCount: [15, 'unsupported operation']
  Got an error for getContentList: [15, 'unsupported operation']
Audio in (extInput:line)
  Got an error for getContentCount: [3, 'illegal argument']
   
	extInput:line
   
	extInput:line?port=1
Home Network (dlna:music)
  Got an error for getContentCount: [3, 'illegal argument']
  Got an error for getContentList: [3, 'illegal argument']

**Comment by rytilahti** [comment] 2018-03-09 19:56
So it is working now? Great! Those errors for getContent* are caused by either 1) the source not being an active source or 2) the source does not support listing the contents (which e.g. cannot be done on line input nor bluetooth audio).

**Comment by rytilahti** [comment] 2018-03-16 19:54
Closing as it is seemingly working, please reopen if this is still a problem.

**Closed as completed by rytilahti** 2018-03-16 19:54 UTC
