### ISSUE TITLE
Got unknowns for Input STR DN1080

### ISSUE THREAD

**Issue by k2v1n58** [rytilahti/python-songpal#21] opened 2018-04-04 15:54 UTC
Hello,
I have these errors using HomeAssistant 0.65-0.66 on Docker (Synology). My amplifier is a STR-DN1080

> Got unknowns for Input: {'outputs': ['extOutput:zone?zone=1', 'extOutput:zone?zone=2']} - please create an issue!
14:12 components/media_player/songpal.py (WARNING)
Got unknowns for Input: {'outputs': ['extOutput:zone?zone=1', 'extOutput:zone?zone=2', 'extOutput:zone?zone=4']} - please create an issue!
14:12 components/media_player/songpal.py (WARNING)
Got unknowns for Input: {'outputs': ['extOutput:zone?zone=1']} - please create an issue!
14:12 components/media_player/songpal.py (WARNING)
Got unknowns for Input: {'outputs': ['extOutput:zone?zone=1', 'extOutput:zone?zone=4']} - please create an issue!
14:12 components/media_player/songpal.py (WARNING)
Got unknowns for Input: {'outputs': ['extOutput:zone?zone=1', 'extOutput:zone?zone=2']} - please create an issue!
14:12 components/media_player/songpal.py (WARNING)
Got unknowns for Input: {'outputs': ['extOutput:zone?zone=1', 'extOutput:zone?zone=2', 'extOutput:zone?zone=4']} - please create an issue!
14:12 components/media_player/songpal.py (WARNING)
Got unknowns for Input: {'outputs': ['extOutput:zone?zone=1', 'extOutput:zone?zone=4']} - please create an issue!
14:12 components/media_player/songpal.py (WARNING)
Got unknowns for Input: {'outputs': ['extOutput:zone?zone=1', 'extOutput:zone?zone=4']} - please create an issue!
14:12 components/media_player/songpal.py (WARNING)
Got unknowns for Input: {'outputs': ['extOutput:zone?zone=2', 'extOutput:zone?zone=4']} - please create an issue!
14:12 components/media_player/songpal.py (WARNING)
Got [Volume(maxVolume=55, minVolume=0, mute='off', output='extOutput:zone?zone=1', step=1, volume=6), Volume(maxVolume=55, minVolume=0, mute='off', output='extOutput:zone?zone=2', step=0, volume=-1), Volume(maxVolume=55, minVolume=0, mute='off', output='extOutput:zone?zone=4', step=0, volume=-1)] volume controls, using the first one
14:12 components/media_player/songpal.py (WARNING)
The device seems to have more than one volume setting.
14:12 components/media_player/songpal.py (WARNING)

**Comment by rytilahti** [comment] 2018-04-08 22:51
Duplicate of #8, fixed in https://github.com/rytilahti/python-songpal/commit/a3c46a5ffe9a7b1c5aac8088899622dd186ac3ed (except for multi zone control).

**Closed as completed by rytilahti** 2018-04-08 22:51 UTC
