### ISSUE TITLE
Errors calling songpal source [STR-DN1080]

### ISSUE THREAD

**Issue by jmbherbert** [rytilahti/python-songpal#11] opened 2018-03-14 05:03 UTC
Hi, calling:

songpal --endpoint=http://192.168.1.27:10000/sony source

Gives me errors - interestingly different ones each time:
The first time I just got error messages:  
[first_call.txt](https://github.com/rytilahti/python-songpal/files/1809647/first_call.txt)

The second time, it errors again, but gives some output:
[second_call.txt](https://github.com/rytilahti/python-songpal/files/1809655/second_call.txt)

**Comment by rytilahti** [comment] 2018-03-16 11:44
Hi and thanks for testing, I just pushed a fix to make it not to give out those warnings as seen in the second call. This will require a bit more work (I think the problem is that it picks a different version to use from those two available ones) to fix it properly, so I'll reopen it.

edit: actually it is calling the same version, so this should be actually fixed already, please reopen if that is not the case.

**Closed as completed** 2018-03-16 12:13 UTC
