### ISSUE TITLE
Error while setting up platform songpal

### ISSUE THREAD

**Issue by meyerluk** [rytilahti/python-songpal#60] opened 2019-10-22 20:09 UTC
since the homeassistant 0.100 update i cannot get the songpal media_player to work again.

HA config:

```
media_player:
    - platform: songpal
      name: lukas_soundbar
      endpoint: http://192.168.107.42:10000/sony
```

after restarting i get this error

```
Error while setting up platform songpal
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/src/homeassistant/homeassistant/components/songpal/media_player.py", line 84, in async_setup_platform
    await device.initialize()
  File "/usr/src/homeassistant/homeassistant/components/songpal/media_player.py", line 148, in initialize
    await self.dev.get_supported_methods()
  File "/usr/local/lib/python3.7/site-packages/songpal/device.py", line 127, in get_supported_methods
    response = await self.request_supported_methods()
  File "/usr/local/lib/python3.7/site-packages/songpal/device.py", line 119, in request_supported_methods
    return await self.create_post_request("getSupportedApiInfo")
  File "/usr/local/lib/python3.7/site-packages/songpal/device.py", line 104, in create_post_request
    res = await res.json()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1031, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url='http://192.168.107.42:10000/sony/guide
```

when calling the method directly with the songpal command i get this error (maybe i'm missing an argument here):
```
> songpal --endpoint http://192.168.107.42:10000/sony command guide getSupportedApiInfo           
Calling guide.getSupportedApiInfo with params None
INFO:songpal.device:Calling guide.getSupportedApiInfo(None)
Error: Got an error for getSupportedApiInfo: [3, 'Illegal Argument']: IllegalArgument (3): Illegal Argument
```

with curl it seems to work:

Request
```
curl -X POST \
  http://192.168.107.42:10000/sony/guide \
  -H 'Content-Type: application/json' \
  -d '{"method": "getSupportedApiInfo", "params": [{}], "id": 1, "version": "1.0"}'
```
Response:
```
{"result":[[{"apis": [{"versions": [{"version": "1.1"}],"name": "getSoundSettings"},{"versions": [{"version": "1.0"}],"name": "getSpeakerSettings"},{"versions": [{"version": "1.1"}],"name": "getVolumeInformation"},{"versions": [{"version": "1.1"}],"name": "setAudioMute"},{"versions": [{"version": "1.1"}],"name": "setAudioVolume"},{"versions": [{"version": "1.1"}],"name": "setSoundSettings"},{"versions": [{"authLevel":"generic","version":"1.0"}],"name": "setSpeakerSettings"},{"name":"switchNotifications","versions":[{"protocols":["websocket:jsonizer"],"version":"1.0"}]}],"service": "audio","protocols": ["xhrpost:jsonizer","websocket:jsonizer"],"notifications": [{"versions": [{"version": "1.0"}],"name": "notifyVolumeInformation"}]}, {"apis": [{"versions": [{"version": "1.0"}],"name": "getAvailablePlaybackFunction"},{"versions": [{"version": "1.0"}],"name": "getBluetoothSettings"},{"versions": [{"version": "1.0"}],"name": "getCurrentExternalTerminalsStatus"},{"versions": [{"version": "1.0"}],"name": "getPlaybackModeSettings"},{"versions": [{"version": "1.2"}],"name": "getPlayingContentInfo"},{"versions": [{"version": "1.0"}],"name": "getSchemeList"},{"versions": [{"version": "1.2"}],"name": "getSourceList"},{"versions": [{"version": "1.0"}],"name": "getSupportedPlaybackFunction"},{"versions": [{"version": "1.1"}],"name": "pausePlayingContent"},{"versions": [{"version": "1.0"}],"name": "scanPlayingContent"},{"versions": [{"authLevel":"generic","version":"1.0"}],"name": "setBluetoothSettings"},{"versions": [{"version": "1.1"}],"name": "setPlaybackModeSettings"},{"versions": [{"version": "1.2"}],"name": "setPlayContent"},{"versions": [{"version": "1.0"}],"name": "setPlayNextContent"},{"versions": [{"version": "1.0"}],"name": "setPlayPreviousContent"},{"versions": [{"version": "1.1"}],"name": "stopPlayingContent"},{"name":"switchNotifications","versions":[{"protocols":["websocket:jsonizer"],"version":"1.0"}]}],"service": "avContent","protocols": ["xhrpost:jsonizer","websocket:jsonizer"],"notifications": [{"versions": [{"version": "1.0"}],"name": "notifyAvailablePlaybackFunction"},{"versions": [{"authLevel": "private","version": "1.0"}],"name": "notifyPlayingContentInfo"}]}, {"apis": [{"versions": [{"version": "1.0"}],"name": "getSupportedApiInfo"}],"service": "guide","protocols": ["websocket:jsonizer"]}, {"apis": [{"versions": [{"authLevel":"generic","version":"1.0"}],"name": "actSWUpdate"},{"versions": [{"version": "1.0"}],"name": "connectBluetoothDevice"},{"versions": [{"version": "1.0"}],"name": "getAlexaDeviceInfo"},{"versions": [{"version": "1.0"}],"name": "getAlexaRegistrationStatus"},{"versions": [{"version": "1.0"}],"name": "getDeviceMiscSettings"},{"versions": [{"version": "1.0"}],"name": "getInterfaceInformation"},{"versions": [{"version": "1.0"}],"name": "getPowerSettings"},{"versions": [{"version": "1.1"}],"name": "getPowerStatus"},{"versions": [{"version": "1.1"}],"name": "getSettingsTree"},{"versions": [{"version": "1.2"}],"name": "getStorageList"},{"versions": [{"version": "1.0"}],"name": "getSWUpdateInfo"},{"versions": [{"version": "1.4"}],"name": "getSystemInformation"},{"versions": [{"version": "1.0"}],"name": "getSystemSupportedFeature"},{"versions": [{"version": "1.0"}],"name": "getWuTangInfo"},{"versions": [{"version": "1.0"}],"name": "setAlexaRegistrationInfo"},{"versions": [{"version": "1.0"}],"name": "setClientInfo"},{"versions": [{"version": "1.0"}],"name": "setDeviceMiscSettings"},{"versions": [{"version": "1.0"}],"name": "setPowerSettings"},{"versions": [{"version": "1.1"}],"name": "setPowerStatus"},{"versions": [{"authLevel":"generic","version":"1.0"}],"name": "setSleepTimerSettings"},{"versions": [{"authLevel":"generic","version": "1.0"}],"name": "setWuTangInfo"},{"versions": [{"version": "1.0"}],"name": "unregistAlexaDevice"},{"versions": [{"version": "1.0"}],"name": "getVoiceCommandGuide"},{"name":"switchNotifications","versions":[{"protocols":["websocket:jsonizer"],"version":"1.0"}]}],"service": "system","protocols": ["xhrpost:jsonizer","websocket:jsonizer"],"notifications": [{"versions": [{"authLevel": "none","version": "1.0"}],"name": "notifyAlexaRegistrationStatus"},{"versions": [{"authLevel": "none","version": "1.0"}],"name": "notifyPowerStatus"},{"versions": [{"authLevel": "none","version": "1.1"}],"name": "notifySettingsUpdate"},{"versions": [{"authLevel": "generic","version": "1.1"}],"name": "notifyStorageStatus"},{"versions": [{"authLevel": "none","version": "1.0"}],"name": "notifySWUpdateInfo"}]}]],"id":1}
```

am i missing something?

**Comment by rytilahti** [comment] 2019-10-22 20:15
Hi, sorry for that. This is a duplicate of #58, which has been fixed in #59 and the newest python-songpal release. I also just recently created https://github.com/home-assistant/home-assistant/pull/28115 to fix it in home-assistant. Could you please see if the newest python-songpal version fixes this (it'd be great to be sure before that PR gets merged, if possible)?

Regarding to that `IllegalArgument` error, you have to supply `{}` as an argument to make it work, otherwise the params will be `[]` which is something unexpected.

**Closed as completed** 2019-10-22 20:16 UTC
Labels: duplicate

**Comment by meyerluk** [comment] 2019-10-23 20:27
thanks for the reply.

it seems to work now with the latest version
```
songpal --endpoint http://192.168.107.42:10000/sony command guide getSupportedApiInfo {}
```
returns the same output as the curl request

**Comment by rytilahti** [comment] 2019-10-23 21:12
Thanks for testing! I'll merge the homeassistant PR to get it fixed for the next release.
